name: indriveclone
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0-167.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.1
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  flutter_otp_text_field: ^1.1.3+2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  shared_preferences: ^2.2.3
  intl_phone_number_input: ^0.7.4
  url_launcher: ^6.3.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/lottie/
    - assets/marker/
    - assets/json/

flutter_native_splash:
  color: "#323943"
  image: assets/image/onboarding.jpeg
  android: true
  ios: true
  web: false
  fill: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.jpeg"
  min_sdk_android: 21
